Repository CSCI-GA-2820-FA22-003/orders, pull requests merged in 2022-12, with the labels that each got.

#60 [Add] Add badge and decrease CI when not necessary
  .github/workflows/bdd.yml
  .github/workflows/tdd.yml
  README.md
Labels: enhancement

#65 Bdd for most ops.
  features/orders.feature
  features/steps/web_steps.py
Labels: enhancement

#71 List all items by date + cleanup
  service/static/js/rest_api.js
  service/templates/index.html
Labels: feature

#76 [Add] reset database by `/reset`
  service/routes.py
Labels: enhancement

#78 [Add] price error handler
  service/common/error_handlers.py
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#79 [Add] BDD retrieve item after behaves
  features/orders.feature
  service/templates/index.html
Labels: enhancement

#83 [Fix] Invalid id/price/quantity/date filter
  service/routes.py
  tests/test_routes.py
Labels: bug

#84 [Docs] Docs for latest APIs.
  README.md
  docs/item/create.md
  docs/item/update.md
  docs/order/create.md
  docs/order/date.md
  docs/order/delete.md
  docs/order/get.md
  docs/order/list.md
  docs/order/price.md
  docs/order/update.md
Labels: documentation

#85 Fix typos in document
  README.md
  docs/item/delete.md
  docs/item/get.md
  docs/order/price.md
Labels: documentation

#86 [Update] Update API docs to latest API
  service/routes.py
  service/templates/index.html
Labels: enhancement
